dist: bionic

matrix:
  include:
    - os: linux
      sudo: required
      env: TARGET_CPU=x64
      addons:
        apt: &x64-apt
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.8
          - g++-4.8
          - libglib2.0-dev
          - libgtk2.0-dev
          - libxtst-dev
          - libxss-dev
          - libpci-dev
          - libdbus-1-dev
          - libgconf2-dev
          - libgnome-keyring-dev
          - libnss3-dev
          - libasound2-dev
          - libpulse-dev
          - libudev-dev

    - os: linux
      sudo: required
      env: TARGET_CPU=x64 CMAKE_BUILD_TYPE=Debug
      addons:
        apt: *x64-apt

language: cpp

before_install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    export CXX="g++-4.8" CC="gcc-4.8"
  fi
- cd ${TRAVIS_BUILD_DIR}
- cmake --version
- pwd
- python --version

install:
- git submodule init
- git submodule update
- mkdir out
- cd out
- cmake -DBUILD_SAMPLE=1 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=. -DTARGET_CPU=$TARGET_CPU ..

script:
    #- make -j 4 package
- make package

before_deploy:
  - export TRAVIS_ARTIFACTS=$(ls libwebrtc-*.tar.gz)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "${TRAVIS_ARTIFACTS}"
  skip_cleanup: true
  on:
    tags: true
    repo: Winddoing/libwebrtc
